# Generated by Django 4.2.16 on 2024-09-30 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_listing_watchlist_user_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='price',
            new_name='start_price',
        ),
    ]
