# Generated by Django 4.2.16 on 2024-09-30 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_price_listing_start_price_listing_current_bid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='current_bid',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
