# Generated by Django 4.2.16 on 2024-09-30 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_last_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='bid_time',
            new_name='time_of_posting',
        ),
    ]
